### ISSUE TITLE
Execution trace data file must be in format version 4 (or later)

### ISSUE THREAD

**Issue by matthew-james** [sebastianbergmann/de-legacy-fy#5]
Hello,

I am using the example arguments and I can't seem to generate a format version 4 trace file.

I originally tried xdebug 2.2.5.

I built xdebug 2.2.7 from source and tried that as well.

I could not find any xdebug documentation explaining how the format version is determined.  This is what I tried:

    //test.php
    <?php
    echo "hello world!";

    php -d xdebug.auto_trace=1 -d xdebug.trace_format=1 -d xdebug.collect_params=5 -d xdebug.collect_return=1 test.php

    cat /tmp/trace.2362852153.xt
    Version: 2.2.7
    File format: 2
    TRACE START [2015-02-13 21:08:30]
    1	0	0	0.000113	222208	{main}	1		/var/www/7.1-Branch/tests/characterization/generate/test.php	0	0
    1	0	1	0.000394	222288
    			0.000697	8240
    TRACE END   [2015-02-13 21:08:30]

My current ini: https://gist.github.com/matthew-james/795dd4a6939c41ff2217

Thanks!
-Matt

**Comment by sebastianbergmann** [comment]
You need to wait for Xdebug 2.3.

**Comment by matthew-james** [comment]
Ah, that explains it.  Thanks!
